"""Initial migration

Revision ID: 53053ddb152a
Revises: 
Create Date: 2023-09-12 10:31:53.119751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53053ddb152a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
